[package]
name = "unsafe-libopus"
authors = ["C2Rust"]
version = "0.0.0"
publish = false
edition = "2021"
autobins = false

[lib]
crate-type = ["staticlib", "rlib"]

[profile.release]
debug = 1

[dependencies]
libc = "0.2"
libc-stdhandle = "0.1.0"
