[workspace]
members = [
]
[package]
name = "libopus-unsafe"
authors = ["C2Rust"]
version = "0.0.0"
publish = false
edition = "2021"
autobins = false

[lib]
crate-type = ["staticlib", "rlib"]

[dependencies]
libc= "0.2"
