[package]
name = "unsafe-libopus"
authors = ["DCNick3"]
version = "0.1.0"
edition = "2021"

repository = "https://github.com/DCNick3/unsafe-libopus"
description = "libopus transpiled to rust by c2rust"

license = "BSD-3-Clause"

[profile.release]
debug = 1

[dependencies]

[dev-dependencies]
libc = "0.2"
libc-stdhandle = "0.1.0"
