[package]
name = "unsafe-libopus"
authors = ["DCNick3"]
version = "0.1.1"
edition = "2021"

repository = "https://github.com/DCNick3/unsafe-libopus"
description = "libopus transpiled to rust by c2rust"

license = "BSD-3-Clause"

[profile.release]
debug = 1

[dependencies]
# for complex numbers impl
num-traits = "0.2.16"
num-complex = "0.4.1"

# for slicing arrays to other arrays
arrayref = "0.3.7"

[dev-dependencies]
# some translated tests haven't been rewritten not to use libc yet
libc = "0.2"
libc-stdhandle = "0.1.0"

insta = "1.29.0"
