#[c2rust::src_loc = "70:9"]
pub const TYPE_NO_VOICE_ACTIVITY: libc::c_int = 0 as libc::c_int;
#[c2rust::src_loc = "142:9"]
pub const MAX_LPC_ORDER: libc::c_int = 16 as libc::c_int;
#[c2rust::src_loc = "143:9"]
pub const MIN_LPC_ORDER: libc::c_int = 10 as libc::c_int;
#[c2rust::src_loc = "90:9"]
pub const MAX_NB_SUBFR: libc::c_int = 4 as libc::c_int;
#[c2rust::src_loc = "168:9"]
pub const SHELL_CODEC_FRAME_LENGTH: libc::c_int = 16 as libc::c_int;
#[c2rust::src_loc = "173:9"]
pub const N_RATE_LEVELS: libc::c_int = 10 as libc::c_int;
#[c2rust::src_loc = "176:9"]
pub const SILK_MAX_PULSES: libc::c_int = 16 as libc::c_int;
#[c2rust::src_loc = "72:9"]
pub const TYPE_VOICED: libc::c_int = 2 as libc::c_int;
#[c2rust::src_loc = "155:9"]
pub const MAX_SHAPE_LPC_ORDER: libc::c_int = 24 as libc::c_int;
#[c2rust::src_loc = "157:9"]
pub const HARM_SHAPE_FIR_TAPS: libc::c_int = 3 as libc::c_int;
#[c2rust::src_loc = "146:9"]
pub const LTP_ORDER: libc::c_int = 5 as libc::c_int;
#[c2rust::src_loc = "180:10"]
pub const NSQ_LPC_BUF_LENGTH: libc::c_int = MAX_LPC_ORDER;
#[c2rust::src_loc = "82:9"]
pub const STEREO_INTERP_LEN_MS: libc::c_int = 8 as libc::c_int;
#[c2rust::src_loc = "112:9"]
pub const LA_SHAPE_MS: libc::c_int = 5 as libc::c_int;
#[c2rust::src_loc = "81:9"]
pub const STEREO_QUANT_SUB_STEPS: libc::c_int = 5 as libc::c_int;
#[c2rust::src_loc = "80:9"]
pub const STEREO_QUANT_TAB_SIZE: libc::c_int = 16 as libc::c_int;
#[c2rust::src_loc = "160:9"]
pub const MAX_DEL_DEC_STATES: libc::c_int = 4 as libc::c_int;
#[c2rust::src_loc = "94:9"]
pub const SUB_FRAME_LENGTH_MS: libc::c_int = 5 as libc::c_int;
#[c2rust::src_loc = "75:9"]
pub const CODE_INDEPENDENTLY: libc::c_int = 0 as libc::c_int;
#[c2rust::src_loc = "77:9"]
pub const CODE_CONDITIONALLY: libc::c_int = 2 as libc::c_int;
#[c2rust::src_loc = "208:9"]
pub const NLSF_QUANT_MAX_AMPLITUDE: libc::c_int = 4 as libc::c_int;
#[c2rust::src_loc = "76:9"]
pub const CODE_INDEPENDENTLY_NO_LTP_SCALING: libc::c_int = 1 as libc::c_int;
#[c2rust::src_loc = "67:9"]
pub const MAX_API_FS_KHZ: libc::c_int = 48 as libc::c_int;
#[c2rust::src_loc = "42:9"]
pub const DECODER_NUM_CHANNELS: libc::c_int = 2 as libc::c_int;
#[c2rust::src_loc = "40:9"]
pub const ENCODER_NUM_CHANNELS: libc::c_int = 2 as libc::c_int;
#[c2rust::src_loc = "135:9"]
pub const QUANT_LEVEL_ADJUST_Q10: libc::c_int = 80 as libc::c_int;
#[c2rust::src_loc = "119:9"]
pub const MIN_QGAIN_DB: libc::c_int = 2 as libc::c_int;
#[c2rust::src_loc = "127:9"]
pub const MIN_DELTA_GAIN_QUANT: libc::c_int = -(4 as libc::c_int);
#[c2rust::src_loc = "123:9"]
pub const N_LEVELS_QGAIN: libc::c_int = 64 as libc::c_int;
#[c2rust::src_loc = "125:9"]
pub const MAX_DELTA_GAIN_QUANT: libc::c_int = 36 as libc::c_int;
#[c2rust::src_loc = "217:9"]
pub const TRANSITION_NA: libc::c_int = 2 as libc::c_int;
#[c2rust::src_loc = "216:9"]
pub const TRANSITION_NB: libc::c_int = 3 as libc::c_int;
#[c2rust::src_loc = "218:9"]
pub const TRANSITION_INT_NUM: libc::c_int = 5 as libc::c_int;
#[c2rust::src_loc = "132:9"]
pub const OFFSET_UVL_Q10: libc::c_int = 100 as libc::c_int;
#[c2rust::src_loc = "133:9"]
pub const OFFSET_UVH_Q10: libc::c_int = 240 as libc::c_int;
#[c2rust::src_loc = "130:9"]
pub const OFFSET_VL_Q10: libc::c_int = 32 as libc::c_int;
#[c2rust::src_loc = "131:9"]
pub const OFFSET_VH_Q10: libc::c_int = 100 as libc::c_int;
#[c2rust::src_loc = "211:9"]
pub const NLSF_QUANT_DEL_DEC_STATES_LOG2: libc::c_int = 2 as libc::c_int;
#[c2rust::src_loc = "212:9"]
pub const NLSF_QUANT_DEL_DEC_STATES: libc::c_int =
    (1 as libc::c_int) << NLSF_QUANT_DEL_DEC_STATES_LOG2;
#[c2rust::src_loc = "209:9"]
pub const NLSF_QUANT_MAX_AMPLITUDE_EXT: libc::c_int = 10 as libc::c_int;
#[c2rust::src_loc = "165:9"]
pub const DECISION_DELAY: libc::c_int = 40 as libc::c_int;
#[c2rust::src_loc = "96:9"]
pub const MAX_FRAME_LENGTH_MS: libc::c_int = SUB_FRAME_LENGTH_MS * MAX_NB_SUBFR;
#[c2rust::src_loc = "215:9"]
pub const TRANSITION_TIME_MS: libc::c_int = 5120 as libc::c_int;
#[c2rust::src_loc = "219:9"]
pub const TRANSITION_FRAMES: libc::c_int = TRANSITION_TIME_MS / MAX_FRAME_LENGTH_MS;
#[c2rust::src_loc = "201:9"]
pub const LSF_COS_TAB_SZ_FIX: libc::c_int = 128 as libc::c_int;
#[c2rust::src_loc = "138:9"]
pub const MAX_LPC_STABILIZE_ITERATIONS: libc::c_int = 16 as libc::c_int;
#[c2rust::src_loc = "139:9"]
pub const MAX_PREDICTION_POWER_GAIN: libc::c_float = 1e4f32;
#[c2rust::src_loc = "226:9"]
pub const CNG_BUF_MASK_MAX: libc::c_int = 255 as libc::c_int;
#[c2rust::src_loc = "71:9"]
pub const TYPE_UNVOICED: libc::c_int = 1 as libc::c_int;
#[c2rust::src_loc = "56:9"]
pub const NB_SPEECH_FRAMES_BEFORE_DTX: libc::c_int = 10 as libc::c_int;
#[c2rust::src_loc = "57:9"]
pub const MAX_CONSECUTIVE_DTX: libc::c_int = 20 as libc::c_int;
#[c2rust::src_loc = "62:9"]
pub const VAD_NO_ACTIVITY: libc::c_int = 0 as libc::c_int;
#[c2rust::src_loc = "223:9"]
pub const BWE_AFTER_LOSS_Q16: libc::c_int = 63570 as libc::c_int;
#[c2rust::src_loc = "140:9"]
pub const MAX_PREDICTION_POWER_GAIN_AFTER_RESET: libc::c_float = 1e2f32;
#[c2rust::src_loc = "185:9"]
pub const VAD_N_BANDS: libc::c_int = 4 as libc::c_int;
#[c2rust::src_loc = "194:9"]
pub const VAD_NEGATIVE_OFFSET_Q5: libc::c_int = 128 as libc::c_int;
#[c2rust::src_loc = "190:9"]
pub const VAD_NOISE_LEVEL_SMOOTH_COEF_Q16: libc::c_int = 1024 as libc::c_int;
#[c2rust::src_loc = "187:9"]
pub const VAD_INTERNAL_SUBFRAMES_LOG2: libc::c_int = 2 as libc::c_int;
#[c2rust::src_loc = "188:9"]
pub const VAD_INTERNAL_SUBFRAMES: libc::c_int = (1 as libc::c_int) << VAD_INTERNAL_SUBFRAMES_LOG2;
#[c2rust::src_loc = "152:9"]
pub const USE_HARM_SHAPING: libc::c_int = 1 as libc::c_int;
#[c2rust::src_loc = "61:9"]
pub const VAD_NO_DECISION: libc::c_int = -(1 as libc::c_int);
#[c2rust::src_loc = "58:9"]
pub const DTX_ACTIVITY_THRESHOLD: libc::c_float = 0.1f32;
